version: '3.8'

services:
  backapp:
    container_name: backapp
    restart: always
    build: .
    environment:
      NODE_ENV: dev
    ports:
      - '5000:3000'
    links:
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: dbmongo
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    logging:
      driver: none
