version: '3.8'

services:
  backapp:
    container_name: backapp
    restart: always
    build:
      context: ./
      target: debug
    environment:
      NODE_ENV: dev
    ports:
      - '5000:3000'
      - 9229:9229
    command: npm run start-debug
    links:
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: dbmongo
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - ./mongo-volume:/data/db

    logging:
      driver: none
